- hosts: webservers
  become: yes
  become_user: root
  tasks:
  - name: Install git
    package:
      name: git
      state: present

  - name: Run update
    apt:
      update_cache: yes

  - name: Install java
    package:
      name: openjdk-11-jdk
    state: latest

  - name: Download Chrome browser
    command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: Install Chrome Browser
    command: apt install ./google-chrome-stable_current_amd64.deb -y

  - name: Run update
    apt:
      update_cache: yes

  - name: download chromedriver
    command: wget https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip

  - name: install unzip
    command: apt install unzip

  - name: unzip chromedriver
    command: unzip chromedriver_linux64.zip

  - name: move chromedriver
    command: mv chromedriver /home/ubuntu/
